# Perfil dev-admin — shell + panel admin (sin módulos de estudio)
VITE_API_URL=
VITE_DEFAULT_MODULE=flashcards
VITE_ENABLE_LANDING=false
VITE_ENABLE_DASHBOARD=true
VITE_ENABLE_FLASHCARDS=false
VITE_ENABLE_PRONOUN_PRACTICE=false
VITE_ENABLE_PRONOUN_REFERENCE=false
VITE_ENABLE_ADMIN=true
VITE_ENABLE_PAYMENTS=false
