# Perfil dev-full — todos los módulos activos
VITE_API_URL=
VITE_DEFAULT_MODULE=flashcards
VITE_ENABLE_LANDING=true
VITE_ENABLE_DASHBOARD=true
VITE_ENABLE_FLASHCARDS=true
VITE_ENABLE_PRONOUN_PRACTICE=true
VITE_ENABLE_PRONOUN_REFERENCE=true
VITE_ENABLE_ADMIN=true
