# Perfil producción/QA — producto flashcards (release dev-flashcards → qa → main)
VITE_API_URL=
VITE_DEFAULT_MODULE=flashcards
VITE_ENABLE_LANDING=true
VITE_ENABLE_DASHBOARD=true
VITE_ENABLE_FLASHCARDS=true
VITE_ENABLE_PRONOUN_PRACTICE=false
VITE_ENABLE_PRONOUN_REFERENCE=false
VITE_ENABLE_ADMIN=true
VITE_ENABLE_PAYMENTS=false
