# Perfil dev-pronoun — shell (admin/auth) + módulo pronoun
VITE_API_URL=
VITE_DEFAULT_MODULE=pronoun
VITE_ENABLE_LANDING=true
VITE_ENABLE_DASHBOARD=true
VITE_ENABLE_FLASHCARDS=false
VITE_ENABLE_PRONOUN_PRACTICE=true
VITE_ENABLE_PRONOUN_REFERENCE=true
VITE_ENABLE_ADMIN=true
VITE_ENABLE_PAYMENTS=false
